### ISSUE TITLE
Tests: not all supported FreeBSD release versions are listed

### ISSUE THREAD

**Issue by 0mp** [ligurio/unreliablefs#78]
Currently, some tests are skipped on FreeBSD. Unfortunately, the only FreeBSD version listed there is `freebsd12`. As a result tests fail on FreeBSD 13.0 for example.

A solution to this could be using ` sys.platform.startswith(...)` to check if we are running on FreeBSD without having to list all the supported versions explicitly.

**Comment by ligurio** [comment]
Sure, it should be fixed.

**Comment by ligurio** [comment]
closes accidentally
